//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

#pragma warning disable 1591

namespace InfragisticsDev.Win.Data {
    
    
    /// <summary>
    ///Represents a strongly typed in-memory cache of data.
    ///</summary>
    [global::System.Serializable()]
    [global::System.ComponentModel.DesignerCategoryAttribute("code")]
    [global::System.ComponentModel.ToolboxItem(true)]
    [global::System.Xml.Serialization.XmlSchemaProviderAttribute("GetTypedDataSetSchema")]
    [global::System.Xml.Serialization.XmlRootAttribute("GroupLayoutDataSet")]
    [global::System.ComponentModel.Design.HelpKeywordAttribute("vs.data.DataSet")]
    public partial class GroupLayoutDataSet : global::System.Data.DataSet {
        
        private ZoneExPropsDataTable tableZoneExProps;
        
        private global::System.Data.SchemaSerializationMode _schemaSerializationMode = global::System.Data.SchemaSerializationMode.IncludeSchema;
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
        public GroupLayoutDataSet() {
            this.BeginInit();
            this.InitClass();
            global::System.ComponentModel.CollectionChangeEventHandler schemaChangedHandler = new global::System.ComponentModel.CollectionChangeEventHandler(this.SchemaChanged);
            base.Tables.CollectionChanged += schemaChangedHandler;
            base.Relations.CollectionChanged += schemaChangedHandler;
            this.EndInit();
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
        protected GroupLayoutDataSet(global::System.Runtime.Serialization.SerializationInfo info, global::System.Runtime.Serialization.StreamingContext context) : 
                base(info, context, false) {
            if ((this.IsBinarySerialized(info, context) == true)) {
                this.InitVars(false);
                global::System.ComponentModel.CollectionChangeEventHandler schemaChangedHandler1 = new global::System.ComponentModel.CollectionChangeEventHandler(this.SchemaChanged);
                this.Tables.CollectionChanged += schemaChangedHandler1;
                this.Relations.CollectionChanged += schemaChangedHandler1;
                return;
            }
            string strSchema = ((string)(info.GetValue("XmlSchema", typeof(string))));
            if ((this.DetermineSchemaSerializationMode(info, context) == global::System.Data.SchemaSerializationMode.IncludeSchema)) {
                global::System.Data.DataSet ds = new global::System.Data.DataSet();
                ds.ReadXmlSchema(new global::System.Xml.XmlTextReader(new global::System.IO.StringReader(strSchema)));
                if ((ds.Tables["ZoneExProps"] != null)) {
                    base.Tables.Add(new ZoneExPropsDataTable(ds.Tables["ZoneExProps"]));
                }
                this.DataSetName = ds.DataSetName;
                this.Prefix = ds.Prefix;
                this.Namespace = ds.Namespace;
                this.Locale = ds.Locale;
                this.CaseSensitive = ds.CaseSensitive;
                this.EnforceConstraints = ds.EnforceConstraints;
                this.Merge(ds, false, global::System.Data.MissingSchemaAction.Add);
                this.InitVars();
            }
            else {
                this.ReadXmlSchema(new global::System.Xml.XmlTextReader(new global::System.IO.StringReader(strSchema)));
            }
            this.GetSerializationData(info, context);
            global::System.ComponentModel.CollectionChangeEventHandler schemaChangedHandler = new global::System.ComponentModel.CollectionChangeEventHandler(this.SchemaChanged);
            base.Tables.CollectionChanged += schemaChangedHandler;
            this.Relations.CollectionChanged += schemaChangedHandler;
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
        [global::System.ComponentModel.Browsable(false)]
        [global::System.ComponentModel.DesignerSerializationVisibility(global::System.ComponentModel.DesignerSerializationVisibility.Content)]
        public ZoneExPropsDataTable ZoneExProps {
            get {
                return this.tableZoneExProps;
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
        [global::System.ComponentModel.BrowsableAttribute(true)]
        [global::System.ComponentModel.DesignerSerializationVisibilityAttribute(global::System.ComponentModel.DesignerSerializationVisibility.Visible)]
        public override global::System.Data.SchemaSerializationMode SchemaSerializationMode {
            get {
                return this._schemaSerializationMode;
            }
            set {
                this._schemaSerializationMode = value;
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
        [global::System.ComponentModel.DesignerSerializationVisibilityAttribute(global::System.ComponentModel.DesignerSerializationVisibility.Hidden)]
        public new global::System.Data.DataTableCollection Tables {
            get {
                return base.Tables;
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
        [global::System.ComponentModel.DesignerSerializationVisibilityAttribute(global::System.ComponentModel.DesignerSerializationVisibility.Hidden)]
        public new global::System.Data.DataRelationCollection Relations {
            get {
                return base.Relations;
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
        protected override void InitializeDerivedDataSet() {
            this.BeginInit();
            this.InitClass();
            this.EndInit();
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
        public override global::System.Data.DataSet Clone() {
            GroupLayoutDataSet cln = ((GroupLayoutDataSet)(base.Clone()));
            cln.InitVars();
            cln.SchemaSerializationMode = this.SchemaSerializationMode;
            return cln;
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
        protected override bool ShouldSerializeTables() {
            return false;
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
        protected override bool ShouldSerializeRelations() {
            return false;
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
        protected override void ReadXmlSerializable(global::System.Xml.XmlReader reader) {
            if ((this.DetermineSchemaSerializationMode(reader) == global::System.Data.SchemaSerializationMode.IncludeSchema)) {
                this.Reset();
                global::System.Data.DataSet ds = new global::System.Data.DataSet();
                ds.ReadXml(reader);
                if ((ds.Tables["ZoneExProps"] != null)) {
                    base.Tables.Add(new ZoneExPropsDataTable(ds.Tables["ZoneExProps"]));
                }
                this.DataSetName = ds.DataSetName;
                this.Prefix = ds.Prefix;
                this.Namespace = ds.Namespace;
                this.Locale = ds.Locale;
                this.CaseSensitive = ds.CaseSensitive;
                this.EnforceConstraints = ds.EnforceConstraints;
                this.Merge(ds, false, global::System.Data.MissingSchemaAction.Add);
                this.InitVars();
            }
            else {
                this.ReadXml(reader);
                this.InitVars();
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
        protected override global::System.Xml.Schema.XmlSchema GetSchemaSerializable() {
            global::System.IO.MemoryStream stream = new global::System.IO.MemoryStream();
            this.WriteXmlSchema(new global::System.Xml.XmlTextWriter(stream, null));
            stream.Position = 0;
            return global::System.Xml.Schema.XmlSchema.Read(new global::System.Xml.XmlTextReader(stream), null);
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
        internal void InitVars() {
            this.InitVars(true);
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
        internal void InitVars(bool initTable) {
            this.tableZoneExProps = ((ZoneExPropsDataTable)(base.Tables["ZoneExProps"]));
            if ((initTable == true)) {
                if ((this.tableZoneExProps != null)) {
                    this.tableZoneExProps.InitVars();
                }
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
        private void InitClass() {
            this.DataSetName = "GroupLayoutDataSet";
            this.Prefix = "";
            this.Namespace = "http://tempuri.org/GroupLayoutDataSet.xsd";
            this.EnforceConstraints = true;
            this.SchemaSerializationMode = global::System.Data.SchemaSerializationMode.IncludeSchema;
            this.tableZoneExProps = new ZoneExPropsDataTable();
            base.Tables.Add(this.tableZoneExProps);
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
        private bool ShouldSerializeZoneExProps() {
            return false;
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
        private void SchemaChanged(object sender, global::System.ComponentModel.CollectionChangeEventArgs e) {
            if ((e.Action == global::System.ComponentModel.CollectionChangeAction.Remove)) {
                this.InitVars();
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
        public static global::System.Xml.Schema.XmlSchemaComplexType GetTypedDataSetSchema(global::System.Xml.Schema.XmlSchemaSet xs) {
            GroupLayoutDataSet ds = new GroupLayoutDataSet();
            global::System.Xml.Schema.XmlSchemaComplexType type = new global::System.Xml.Schema.XmlSchemaComplexType();
            global::System.Xml.Schema.XmlSchemaSequence sequence = new global::System.Xml.Schema.XmlSchemaSequence();
            global::System.Xml.Schema.XmlSchemaAny any = new global::System.Xml.Schema.XmlSchemaAny();
            any.Namespace = ds.Namespace;
            sequence.Items.Add(any);
            type.Particle = sequence;
            global::System.Xml.Schema.XmlSchema dsSchema = ds.GetSchemaSerializable();
            if (xs.Contains(dsSchema.TargetNamespace)) {
                global::System.IO.MemoryStream s1 = new global::System.IO.MemoryStream();
                global::System.IO.MemoryStream s2 = new global::System.IO.MemoryStream();
                try {
                    global::System.Xml.Schema.XmlSchema schema = null;
                    dsSchema.Write(s1);
                    for (global::System.Collections.IEnumerator schemas = xs.Schemas(dsSchema.TargetNamespace).GetEnumerator(); schemas.MoveNext(); ) {
                        schema = ((global::System.Xml.Schema.XmlSchema)(schemas.Current));
                        s2.SetLength(0);
                        schema.Write(s2);
                        if ((s1.Length == s2.Length)) {
                            s1.Position = 0;
                            s2.Position = 0;
                            for (; ((s1.Position != s1.Length) 
                                        && (s1.ReadByte() == s2.ReadByte())); ) {
                                ;
                            }
                            if ((s1.Position == s1.Length)) {
                                return type;
                            }
                        }
                    }
                }
                finally {
                    if ((s1 != null)) {
                        s1.Close();
                    }
                    if ((s2 != null)) {
                        s2.Close();
                    }
                }
            }
            xs.Add(dsSchema);
            return type;
        }
        
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
        public delegate void ZoneExPropsRowChangeEventHandler(object sender, ZoneExPropsRowChangeEvent e);
        
        /// <summary>
        ///Represents the strongly named DataTable class.
        ///</summary>
        [global::System.Serializable()]
        [global::System.Xml.Serialization.XmlSchemaProviderAttribute("GetTypedTableSchema")]
        public partial class ZoneExPropsDataTable : global::System.Data.TypedTableBase<ZoneExPropsRow> {
            
            private global::System.Data.DataColumn columnSpaces;
            
            private global::System.Data.DataColumn columnContained_building_stories;
            
            private global::System.Data.DataColumn columnArea;
            
            private global::System.Data.DataColumn columnVolume;
            
            private global::System.Data.DataColumn columnOccupancy_Template;
            
            private global::System.Data.DataColumn columnZone_Daylighting_Group;
            
            private global::System.Data.DataColumn columnZone_Natural_Ventilation_Group;
            
            private global::System.Data.DataColumn columnZone_SHW_Group;
            
            private global::System.Data.DataColumn columnZone_RFG_Group;
            
            private global::System.Data.DataColumn columnZone_HVAC_Group_Name;
            
            private global::System.Data.DataColumn _columnZone_HVAC_Group_Name_1;
            
            private global::System.Data.DataColumn columnZone_HVAC_Group_Template;
            
            private global::System.Data.DataColumn columnAir_Loop_Name;
            
            private global::System.Data.DataColumn columnAir_Loop_Template;
            
            private global::System.Data.DataColumn columnWater_Loop_Name;
            
            private global::System.Data.DataColumn columnLibraryName;
            
            private global::System.Data.DataColumn _columnSpaces_1;
            
            private global::System.Data.DataColumn _columnContained_building_stories_1;
            
            private global::System.Data.DataColumn _columnOccupancy_Template_1;
            
            private global::System.Data.DataColumn _columnZone_Natural_Ventilation_Group_1;
            
            private global::System.Data.DataColumn _columnZone_SHW_Group_1;
            
            private global::System.Data.DataColumn _columnZone_RFG_Group_1;
            
            private global::System.Data.DataColumn _columnZone_HVAC_Group_Template_1;
            
            private global::System.Data.DataColumn _columnAir_Loop_Name_1;
            
            private global::System.Data.DataColumn _columnAir_Loop_Template_1;
            
            private global::System.Data.DataColumn _columnWater_Loop_Name_1;
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public ZoneExPropsDataTable() {
                this.TableName = "ZoneExProps";
                this.BeginInit();
                this.InitClass();
                this.EndInit();
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            internal ZoneExPropsDataTable(global::System.Data.DataTable table) {
                this.TableName = table.TableName;
                if ((table.CaseSensitive != table.DataSet.CaseSensitive)) {
                    this.CaseSensitive = table.CaseSensitive;
                }
                if ((table.Locale.ToString() != table.DataSet.Locale.ToString())) {
                    this.Locale = table.Locale;
                }
                if ((table.Namespace != table.DataSet.Namespace)) {
                    this.Namespace = table.Namespace;
                }
                this.Prefix = table.Prefix;
                this.MinimumCapacity = table.MinimumCapacity;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            protected ZoneExPropsDataTable(global::System.Runtime.Serialization.SerializationInfo info, global::System.Runtime.Serialization.StreamingContext context) : 
                    base(info, context) {
                this.InitVars();
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public global::System.Data.DataColumn SpacesColumn {
                get {
                    return this.columnSpaces;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public global::System.Data.DataColumn Contained_building_storiesColumn {
                get {
                    return this.columnContained_building_stories;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public global::System.Data.DataColumn AreaColumn {
                get {
                    return this.columnArea;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public global::System.Data.DataColumn VolumeColumn {
                get {
                    return this.columnVolume;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public global::System.Data.DataColumn Occupancy_TemplateColumn {
                get {
                    return this.columnOccupancy_Template;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public global::System.Data.DataColumn Zone_Daylighting_GroupColumn {
                get {
                    return this.columnZone_Daylighting_Group;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public global::System.Data.DataColumn Zone_Natural_Ventilation_GroupColumn {
                get {
                    return this.columnZone_Natural_Ventilation_Group;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public global::System.Data.DataColumn Zone_SHW_GroupColumn {
                get {
                    return this.columnZone_SHW_Group;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public global::System.Data.DataColumn Zone_RFG_GroupColumn {
                get {
                    return this.columnZone_RFG_Group;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public global::System.Data.DataColumn Zone_HVAC_Group_NameColumn {
                get {
                    return this.columnZone_HVAC_Group_Name;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public global::System.Data.DataColumn _Zone_HVAC_Group_Name_1Column {
                get {
                    return this._columnZone_HVAC_Group_Name_1;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public global::System.Data.DataColumn Zone_HVAC_Group_TemplateColumn {
                get {
                    return this.columnZone_HVAC_Group_Template;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public global::System.Data.DataColumn Air_Loop_NameColumn {
                get {
                    return this.columnAir_Loop_Name;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public global::System.Data.DataColumn Air_Loop_TemplateColumn {
                get {
                    return this.columnAir_Loop_Template;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public global::System.Data.DataColumn Water_Loop_NameColumn {
                get {
                    return this.columnWater_Loop_Name;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public global::System.Data.DataColumn LibraryNameColumn {
                get {
                    return this.columnLibraryName;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public global::System.Data.DataColumn _Spaces_1Column {
                get {
                    return this._columnSpaces_1;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public global::System.Data.DataColumn _Contained_building_stories_1Column {
                get {
                    return this._columnContained_building_stories_1;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public global::System.Data.DataColumn _Occupancy_Template_1Column {
                get {
                    return this._columnOccupancy_Template_1;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public global::System.Data.DataColumn _Zone_Natural_Ventilation_Group_1Column {
                get {
                    return this._columnZone_Natural_Ventilation_Group_1;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public global::System.Data.DataColumn _Zone_SHW_Group_1Column {
                get {
                    return this._columnZone_SHW_Group_1;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public global::System.Data.DataColumn _Zone_RFG_Group_1Column {
                get {
                    return this._columnZone_RFG_Group_1;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public global::System.Data.DataColumn _Zone_HVAC_Group_Template_1Column {
                get {
                    return this._columnZone_HVAC_Group_Template_1;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public global::System.Data.DataColumn _Air_Loop_Name_1Column {
                get {
                    return this._columnAir_Loop_Name_1;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public global::System.Data.DataColumn _Air_Loop_Template_1Column {
                get {
                    return this._columnAir_Loop_Template_1;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public global::System.Data.DataColumn _Water_Loop_Name_1Column {
                get {
                    return this._columnWater_Loop_Name_1;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            [global::System.ComponentModel.Browsable(false)]
            public int Count {
                get {
                    return this.Rows.Count;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public ZoneExPropsRow this[int index] {
                get {
                    return ((ZoneExPropsRow)(this.Rows[index]));
                }
            }
            
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public event ZoneExPropsRowChangeEventHandler ZoneExPropsRowChanging;
            
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public event ZoneExPropsRowChangeEventHandler ZoneExPropsRowChanged;
            
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public event ZoneExPropsRowChangeEventHandler ZoneExPropsRowDeleting;
            
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public event ZoneExPropsRowChangeEventHandler ZoneExPropsRowDeleted;
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public void AddZoneExPropsRow(ZoneExPropsRow row) {
                this.Rows.Add(row);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public ZoneExPropsRow AddZoneExPropsRow(
                        string Spaces, 
                        string Contained_building_stories, 
                        string Area, 
                        string Volume, 
                        string Occupancy_Template, 
                        string Zone_Daylighting_Group, 
                        string Zone_Natural_Ventilation_Group, 
                        string Zone_SHW_Group, 
                        string Zone_RFG_Group, 
                        string Zone_HVAC_Group_Name, 
                        string _Zone_HVAC_Group_Name_1, 
                        string Zone_HVAC_Group_Template, 
                        string Air_Loop_Name, 
                        string Air_Loop_Template, 
                        string Water_Loop_Name, 
                        string LibraryName, 
                        string _Spaces_1, 
                        string _Contained_building_stories_1, 
                        string _Occupancy_Template_1, 
                        string _Zone_Natural_Ventilation_Group_1, 
                        string _Zone_SHW_Group_1, 
                        string _Zone_RFG_Group_1, 
                        string _Zone_HVAC_Group_Template_1, 
                        string _Air_Loop_Name_1, 
                        string _Air_Loop_Template_1, 
                        string _Water_Loop_Name_1) {
                ZoneExPropsRow rowZoneExPropsRow = ((ZoneExPropsRow)(this.NewRow()));
                object[] columnValuesArray = new object[] {
                        Spaces,
                        Contained_building_stories,
                        Area,
                        Volume,
                        Occupancy_Template,
                        Zone_Daylighting_Group,
                        Zone_Natural_Ventilation_Group,
                        Zone_SHW_Group,
                        Zone_RFG_Group,
                        Zone_HVAC_Group_Name,
                        _Zone_HVAC_Group_Name_1,
                        Zone_HVAC_Group_Template,
                        Air_Loop_Name,
                        Air_Loop_Template,
                        Water_Loop_Name,
                        LibraryName,
                        _Spaces_1,
                        _Contained_building_stories_1,
                        _Occupancy_Template_1,
                        _Zone_Natural_Ventilation_Group_1,
                        _Zone_SHW_Group_1,
                        _Zone_RFG_Group_1,
                        _Zone_HVAC_Group_Template_1,
                        _Air_Loop_Name_1,
                        _Air_Loop_Template_1,
                        _Water_Loop_Name_1};
                rowZoneExPropsRow.ItemArray = columnValuesArray;
                this.Rows.Add(rowZoneExPropsRow);
                return rowZoneExPropsRow;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public override global::System.Data.DataTable Clone() {
                ZoneExPropsDataTable cln = ((ZoneExPropsDataTable)(base.Clone()));
                cln.InitVars();
                return cln;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            protected override global::System.Data.DataTable CreateInstance() {
                return new ZoneExPropsDataTable();
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            internal void InitVars() {
                this.columnSpaces = base.Columns["Spaces"];
                this.columnContained_building_stories = base.Columns["Contained building stories"];
                this.columnArea = base.Columns["Area"];
                this.columnVolume = base.Columns["Volume"];
                this.columnOccupancy_Template = base.Columns["Occupancy Template"];
                this.columnZone_Daylighting_Group = base.Columns["Zone Daylighting Group"];
                this.columnZone_Natural_Ventilation_Group = base.Columns["Zone Natural Ventilation Group"];
                this.columnZone_SHW_Group = base.Columns["Zone SHW Group"];
                this.columnZone_RFG_Group = base.Columns["Zone RFG Group"];
                this.columnZone_HVAC_Group_Name = base.Columns["Zone HVAC Group Name"];
                this._columnZone_HVAC_Group_Name_1 = base.Columns["Zone HVAC Group Name-1"];
                this.columnZone_HVAC_Group_Template = base.Columns["Zone HVAC Group Template"];
                this.columnAir_Loop_Name = base.Columns["Air Loop Name"];
                this.columnAir_Loop_Template = base.Columns["Air Loop Template"];
                this.columnWater_Loop_Name = base.Columns["Water Loop Name"];
                this.columnLibraryName = base.Columns["LibraryName"];
                this._columnSpaces_1 = base.Columns["Spaces-1"];
                this._columnContained_building_stories_1 = base.Columns["Contained building stories-1"];
                this._columnOccupancy_Template_1 = base.Columns["Occupancy Template-1"];
                this._columnZone_Natural_Ventilation_Group_1 = base.Columns["Zone Natural Ventilation Group-1"];
                this._columnZone_SHW_Group_1 = base.Columns["Zone SHW Group-1"];
                this._columnZone_RFG_Group_1 = base.Columns["Zone RFG Group-1"];
                this._columnZone_HVAC_Group_Template_1 = base.Columns["Zone HVAC Group Template-1"];
                this._columnAir_Loop_Name_1 = base.Columns["Air Loop Name-1"];
                this._columnAir_Loop_Template_1 = base.Columns["Air Loop Template-1"];
                this._columnWater_Loop_Name_1 = base.Columns["Water Loop Name-1"];
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            private void InitClass() {
                this.columnSpaces = new global::System.Data.DataColumn("Spaces", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnSpaces);
                this.columnContained_building_stories = new global::System.Data.DataColumn("Contained building stories", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnContained_building_stories);
                this.columnArea = new global::System.Data.DataColumn("Area", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnArea);
                this.columnVolume = new global::System.Data.DataColumn("Volume", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnVolume);
                this.columnOccupancy_Template = new global::System.Data.DataColumn("Occupancy Template", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnOccupancy_Template);
                this.columnZone_Daylighting_Group = new global::System.Data.DataColumn("Zone Daylighting Group", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnZone_Daylighting_Group);
                this.columnZone_Natural_Ventilation_Group = new global::System.Data.DataColumn("Zone Natural Ventilation Group", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnZone_Natural_Ventilation_Group);
                this.columnZone_SHW_Group = new global::System.Data.DataColumn("Zone SHW Group", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnZone_SHW_Group);
                this.columnZone_RFG_Group = new global::System.Data.DataColumn("Zone RFG Group", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnZone_RFG_Group);
                this.columnZone_HVAC_Group_Name = new global::System.Data.DataColumn("Zone HVAC Group Name", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnZone_HVAC_Group_Name);
                this._columnZone_HVAC_Group_Name_1 = new global::System.Data.DataColumn("Zone HVAC Group Name-1", typeof(string), null, global::System.Data.MappingType.Element);
                this._columnZone_HVAC_Group_Name_1.ExtendedProperties.Add("Generator_ColumnVarNameInTable", "_columnZone_HVAC_Group_Name_1");
                this._columnZone_HVAC_Group_Name_1.ExtendedProperties.Add("Generator_UserColumnName", "Zone HVAC Group Name-1");
                base.Columns.Add(this._columnZone_HVAC_Group_Name_1);
                this.columnZone_HVAC_Group_Template = new global::System.Data.DataColumn("Zone HVAC Group Template", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnZone_HVAC_Group_Template);
                this.columnAir_Loop_Name = new global::System.Data.DataColumn("Air Loop Name", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnAir_Loop_Name);
                this.columnAir_Loop_Template = new global::System.Data.DataColumn("Air Loop Template", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnAir_Loop_Template);
                this.columnWater_Loop_Name = new global::System.Data.DataColumn("Water Loop Name", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnWater_Loop_Name);
                this.columnLibraryName = new global::System.Data.DataColumn("LibraryName", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnLibraryName);
                this._columnSpaces_1 = new global::System.Data.DataColumn("Spaces-1", typeof(string), null, global::System.Data.MappingType.Element);
                this._columnSpaces_1.ExtendedProperties.Add("Generator_ColumnVarNameInTable", "_columnSpaces_1");
                this._columnSpaces_1.ExtendedProperties.Add("Generator_UserColumnName", "Spaces-1");
                base.Columns.Add(this._columnSpaces_1);
                this._columnContained_building_stories_1 = new global::System.Data.DataColumn("Contained building stories-1", typeof(string), null, global::System.Data.MappingType.Element);
                this._columnContained_building_stories_1.ExtendedProperties.Add("Generator_ColumnVarNameInTable", "_columnContained_building_stories_1");
                this._columnContained_building_stories_1.ExtendedProperties.Add("Generator_UserColumnName", "Contained building stories-1");
                base.Columns.Add(this._columnContained_building_stories_1);
                this._columnOccupancy_Template_1 = new global::System.Data.DataColumn("Occupancy Template-1", typeof(string), null, global::System.Data.MappingType.Element);
                this._columnOccupancy_Template_1.ExtendedProperties.Add("Generator_ColumnVarNameInTable", "_columnOccupancy_Template_1");
                this._columnOccupancy_Template_1.ExtendedProperties.Add("Generator_UserColumnName", "Occupancy Template-1");
                base.Columns.Add(this._columnOccupancy_Template_1);
                this._columnZone_Natural_Ventilation_Group_1 = new global::System.Data.DataColumn("Zone Natural Ventilation Group-1", typeof(string), null, global::System.Data.MappingType.Element);
                this._columnZone_Natural_Ventilation_Group_1.ExtendedProperties.Add("Generator_ColumnVarNameInTable", "_columnZone_Natural_Ventilation_Group_1");
                this._columnZone_Natural_Ventilation_Group_1.ExtendedProperties.Add("Generator_UserColumnName", "Zone Natural Ventilation Group-1");
                base.Columns.Add(this._columnZone_Natural_Ventilation_Group_1);
                this._columnZone_SHW_Group_1 = new global::System.Data.DataColumn("Zone SHW Group-1", typeof(string), null, global::System.Data.MappingType.Element);
                this._columnZone_SHW_Group_1.ExtendedProperties.Add("Generator_ColumnVarNameInTable", "_columnZone_SHW_Group_1");
                this._columnZone_SHW_Group_1.ExtendedProperties.Add("Generator_UserColumnName", "Zone SHW Group-1");
                base.Columns.Add(this._columnZone_SHW_Group_1);
                this._columnZone_RFG_Group_1 = new global::System.Data.DataColumn("Zone RFG Group-1", typeof(string), null, global::System.Data.MappingType.Element);
                this._columnZone_RFG_Group_1.ExtendedProperties.Add("Generator_ColumnVarNameInTable", "_columnZone_RFG_Group_1");
                this._columnZone_RFG_Group_1.ExtendedProperties.Add("Generator_UserColumnName", "Zone RFG Group-1");
                base.Columns.Add(this._columnZone_RFG_Group_1);
                this._columnZone_HVAC_Group_Template_1 = new global::System.Data.DataColumn("Zone HVAC Group Template-1", typeof(string), null, global::System.Data.MappingType.Element);
                this._columnZone_HVAC_Group_Template_1.ExtendedProperties.Add("Generator_ColumnVarNameInTable", "_columnZone_HVAC_Group_Template_1");
                this._columnZone_HVAC_Group_Template_1.ExtendedProperties.Add("Generator_UserColumnName", "Zone HVAC Group Template-1");
                base.Columns.Add(this._columnZone_HVAC_Group_Template_1);
                this._columnAir_Loop_Name_1 = new global::System.Data.DataColumn("Air Loop Name-1", typeof(string), null, global::System.Data.MappingType.Element);
                this._columnAir_Loop_Name_1.ExtendedProperties.Add("Generator_ColumnVarNameInTable", "_columnAir_Loop_Name_1");
                this._columnAir_Loop_Name_1.ExtendedProperties.Add("Generator_UserColumnName", "Air Loop Name-1");
                base.Columns.Add(this._columnAir_Loop_Name_1);
                this._columnAir_Loop_Template_1 = new global::System.Data.DataColumn("Air Loop Template-1", typeof(string), null, global::System.Data.MappingType.Element);
                this._columnAir_Loop_Template_1.ExtendedProperties.Add("Generator_ColumnVarNameInTable", "_columnAir_Loop_Template_1");
                this._columnAir_Loop_Template_1.ExtendedProperties.Add("Generator_UserColumnName", "Air Loop Template-1");
                base.Columns.Add(this._columnAir_Loop_Template_1);
                this._columnWater_Loop_Name_1 = new global::System.Data.DataColumn("Water Loop Name-1", typeof(string), null, global::System.Data.MappingType.Element);
                this._columnWater_Loop_Name_1.ExtendedProperties.Add("Generator_ColumnVarNameInTable", "_columnWater_Loop_Name_1");
                this._columnWater_Loop_Name_1.ExtendedProperties.Add("Generator_UserColumnName", "Water Loop Name-1");
                base.Columns.Add(this._columnWater_Loop_Name_1);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public ZoneExPropsRow NewZoneExPropsRow() {
                return ((ZoneExPropsRow)(this.NewRow()));
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            protected override global::System.Data.DataRow NewRowFromBuilder(global::System.Data.DataRowBuilder builder) {
                return new ZoneExPropsRow(builder);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            protected override global::System.Type GetRowType() {
                return typeof(ZoneExPropsRow);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            protected override void OnRowChanged(global::System.Data.DataRowChangeEventArgs e) {
                base.OnRowChanged(e);
                if ((this.ZoneExPropsRowChanged != null)) {
                    this.ZoneExPropsRowChanged(this, new ZoneExPropsRowChangeEvent(((ZoneExPropsRow)(e.Row)), e.Action));
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            protected override void OnRowChanging(global::System.Data.DataRowChangeEventArgs e) {
                base.OnRowChanging(e);
                if ((this.ZoneExPropsRowChanging != null)) {
                    this.ZoneExPropsRowChanging(this, new ZoneExPropsRowChangeEvent(((ZoneExPropsRow)(e.Row)), e.Action));
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            protected override void OnRowDeleted(global::System.Data.DataRowChangeEventArgs e) {
                base.OnRowDeleted(e);
                if ((this.ZoneExPropsRowDeleted != null)) {
                    this.ZoneExPropsRowDeleted(this, new ZoneExPropsRowChangeEvent(((ZoneExPropsRow)(e.Row)), e.Action));
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            protected override void OnRowDeleting(global::System.Data.DataRowChangeEventArgs e) {
                base.OnRowDeleting(e);
                if ((this.ZoneExPropsRowDeleting != null)) {
                    this.ZoneExPropsRowDeleting(this, new ZoneExPropsRowChangeEvent(((ZoneExPropsRow)(e.Row)), e.Action));
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public void RemoveZoneExPropsRow(ZoneExPropsRow row) {
                this.Rows.Remove(row);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public static global::System.Xml.Schema.XmlSchemaComplexType GetTypedTableSchema(global::System.Xml.Schema.XmlSchemaSet xs) {
                global::System.Xml.Schema.XmlSchemaComplexType type = new global::System.Xml.Schema.XmlSchemaComplexType();
                global::System.Xml.Schema.XmlSchemaSequence sequence = new global::System.Xml.Schema.XmlSchemaSequence();
                GroupLayoutDataSet ds = new GroupLayoutDataSet();
                global::System.Xml.Schema.XmlSchemaAny any1 = new global::System.Xml.Schema.XmlSchemaAny();
                any1.Namespace = "http://www.w3.org/2001/XMLSchema";
                any1.MinOccurs = new decimal(0);
                any1.MaxOccurs = decimal.MaxValue;
                any1.ProcessContents = global::System.Xml.Schema.XmlSchemaContentProcessing.Lax;
                sequence.Items.Add(any1);
                global::System.Xml.Schema.XmlSchemaAny any2 = new global::System.Xml.Schema.XmlSchemaAny();
                any2.Namespace = "urn:schemas-microsoft-com:xml-diffgram-v1";
                any2.MinOccurs = new decimal(1);
                any2.ProcessContents = global::System.Xml.Schema.XmlSchemaContentProcessing.Lax;
                sequence.Items.Add(any2);
                global::System.Xml.Schema.XmlSchemaAttribute attribute1 = new global::System.Xml.Schema.XmlSchemaAttribute();
                attribute1.Name = "namespace";
                attribute1.FixedValue = ds.Namespace;
                type.Attributes.Add(attribute1);
                global::System.Xml.Schema.XmlSchemaAttribute attribute2 = new global::System.Xml.Schema.XmlSchemaAttribute();
                attribute2.Name = "tableTypeName";
                attribute2.FixedValue = "ZoneExPropsDataTable";
                type.Attributes.Add(attribute2);
                type.Particle = sequence;
                global::System.Xml.Schema.XmlSchema dsSchema = ds.GetSchemaSerializable();
                if (xs.Contains(dsSchema.TargetNamespace)) {
                    global::System.IO.MemoryStream s1 = new global::System.IO.MemoryStream();
                    global::System.IO.MemoryStream s2 = new global::System.IO.MemoryStream();
                    try {
                        global::System.Xml.Schema.XmlSchema schema = null;
                        dsSchema.Write(s1);
                        for (global::System.Collections.IEnumerator schemas = xs.Schemas(dsSchema.TargetNamespace).GetEnumerator(); schemas.MoveNext(); ) {
                            schema = ((global::System.Xml.Schema.XmlSchema)(schemas.Current));
                            s2.SetLength(0);
                            schema.Write(s2);
                            if ((s1.Length == s2.Length)) {
                                s1.Position = 0;
                                s2.Position = 0;
                                for (; ((s1.Position != s1.Length) 
                                            && (s1.ReadByte() == s2.ReadByte())); ) {
                                    ;
                                }
                                if ((s1.Position == s1.Length)) {
                                    return type;
                                }
                            }
                        }
                    }
                    finally {
                        if ((s1 != null)) {
                            s1.Close();
                        }
                        if ((s2 != null)) {
                            s2.Close();
                        }
                    }
                }
                xs.Add(dsSchema);
                return type;
            }
        }
        
        /// <summary>
        ///Represents strongly named DataRow class.
        ///</summary>
        public partial class ZoneExPropsRow : global::System.Data.DataRow {
            
            private ZoneExPropsDataTable tableZoneExProps;
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            internal ZoneExPropsRow(global::System.Data.DataRowBuilder rb) : 
                    base(rb) {
                this.tableZoneExProps = ((ZoneExPropsDataTable)(this.Table));
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public string Spaces {
                get {
                    try {
                        return ((string)(this[this.tableZoneExProps.SpacesColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'Spaces\' in table \'ZoneExProps\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tableZoneExProps.SpacesColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public string Contained_building_stories {
                get {
                    try {
                        return ((string)(this[this.tableZoneExProps.Contained_building_storiesColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'Contained building stories\' in table \'ZoneExProps\' is DBNul" +
                                "l.", e);
                    }
                }
                set {
                    this[this.tableZoneExProps.Contained_building_storiesColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public string Area {
                get {
                    try {
                        return ((string)(this[this.tableZoneExProps.AreaColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'Area\' in table \'ZoneExProps\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tableZoneExProps.AreaColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public string Volume {
                get {
                    try {
                        return ((string)(this[this.tableZoneExProps.VolumeColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'Volume\' in table \'ZoneExProps\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tableZoneExProps.VolumeColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public string Occupancy_Template {
                get {
                    try {
                        return ((string)(this[this.tableZoneExProps.Occupancy_TemplateColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'Occupancy Template\' in table \'ZoneExProps\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tableZoneExProps.Occupancy_TemplateColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public string Zone_Daylighting_Group {
                get {
                    try {
                        return ((string)(this[this.tableZoneExProps.Zone_Daylighting_GroupColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'Zone Daylighting Group\' in table \'ZoneExProps\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tableZoneExProps.Zone_Daylighting_GroupColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public string Zone_Natural_Ventilation_Group {
                get {
                    try {
                        return ((string)(this[this.tableZoneExProps.Zone_Natural_Ventilation_GroupColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'Zone Natural Ventilation Group\' in table \'ZoneExProps\' is D" +
                                "BNull.", e);
                    }
                }
                set {
                    this[this.tableZoneExProps.Zone_Natural_Ventilation_GroupColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public string Zone_SHW_Group {
                get {
                    try {
                        return ((string)(this[this.tableZoneExProps.Zone_SHW_GroupColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'Zone SHW Group\' in table \'ZoneExProps\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tableZoneExProps.Zone_SHW_GroupColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public string Zone_RFG_Group {
                get {
                    try {
                        return ((string)(this[this.tableZoneExProps.Zone_RFG_GroupColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'Zone RFG Group\' in table \'ZoneExProps\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tableZoneExProps.Zone_RFG_GroupColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public string Zone_HVAC_Group_Name {
                get {
                    try {
                        return ((string)(this[this.tableZoneExProps.Zone_HVAC_Group_NameColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'Zone HVAC Group Name\' in table \'ZoneExProps\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tableZoneExProps.Zone_HVAC_Group_NameColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public string _Zone_HVAC_Group_Name_1 {
                get {
                    try {
                        return ((string)(this[this.tableZoneExProps._Zone_HVAC_Group_Name_1Column]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'Zone HVAC Group Name-1\' in table \'ZoneExProps\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tableZoneExProps._Zone_HVAC_Group_Name_1Column] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public string Zone_HVAC_Group_Template {
                get {
                    try {
                        return ((string)(this[this.tableZoneExProps.Zone_HVAC_Group_TemplateColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'Zone HVAC Group Template\' in table \'ZoneExProps\' is DBNull." +
                                "", e);
                    }
                }
                set {
                    this[this.tableZoneExProps.Zone_HVAC_Group_TemplateColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public string Air_Loop_Name {
                get {
                    try {
                        return ((string)(this[this.tableZoneExProps.Air_Loop_NameColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'Air Loop Name\' in table \'ZoneExProps\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tableZoneExProps.Air_Loop_NameColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public string Air_Loop_Template {
                get {
                    try {
                        return ((string)(this[this.tableZoneExProps.Air_Loop_TemplateColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'Air Loop Template\' in table \'ZoneExProps\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tableZoneExProps.Air_Loop_TemplateColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public string Water_Loop_Name {
                get {
                    try {
                        return ((string)(this[this.tableZoneExProps.Water_Loop_NameColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'Water Loop Name\' in table \'ZoneExProps\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tableZoneExProps.Water_Loop_NameColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public string LibraryName {
                get {
                    try {
                        return ((string)(this[this.tableZoneExProps.LibraryNameColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'LibraryName\' in table \'ZoneExProps\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tableZoneExProps.LibraryNameColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public string _Spaces_1 {
                get {
                    try {
                        return ((string)(this[this.tableZoneExProps._Spaces_1Column]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'Spaces-1\' in table \'ZoneExProps\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tableZoneExProps._Spaces_1Column] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public string _Contained_building_stories_1 {
                get {
                    try {
                        return ((string)(this[this.tableZoneExProps._Contained_building_stories_1Column]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'Contained building stories-1\' in table \'ZoneExProps\' is DBN" +
                                "ull.", e);
                    }
                }
                set {
                    this[this.tableZoneExProps._Contained_building_stories_1Column] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public string _Occupancy_Template_1 {
                get {
                    try {
                        return ((string)(this[this.tableZoneExProps._Occupancy_Template_1Column]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'Occupancy Template-1\' in table \'ZoneExProps\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tableZoneExProps._Occupancy_Template_1Column] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public string _Zone_Natural_Ventilation_Group_1 {
                get {
                    try {
                        return ((string)(this[this.tableZoneExProps._Zone_Natural_Ventilation_Group_1Column]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'Zone Natural Ventilation Group-1\' in table \'ZoneExProps\' is" +
                                " DBNull.", e);
                    }
                }
                set {
                    this[this.tableZoneExProps._Zone_Natural_Ventilation_Group_1Column] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public string _Zone_SHW_Group_1 {
                get {
                    try {
                        return ((string)(this[this.tableZoneExProps._Zone_SHW_Group_1Column]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'Zone SHW Group-1\' in table \'ZoneExProps\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tableZoneExProps._Zone_SHW_Group_1Column] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public string _Zone_RFG_Group_1 {
                get {
                    try {
                        return ((string)(this[this.tableZoneExProps._Zone_RFG_Group_1Column]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'Zone RFG Group-1\' in table \'ZoneExProps\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tableZoneExProps._Zone_RFG_Group_1Column] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public string _Zone_HVAC_Group_Template_1 {
                get {
                    try {
                        return ((string)(this[this.tableZoneExProps._Zone_HVAC_Group_Template_1Column]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'Zone HVAC Group Template-1\' in table \'ZoneExProps\' is DBNul" +
                                "l.", e);
                    }
                }
                set {
                    this[this.tableZoneExProps._Zone_HVAC_Group_Template_1Column] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public string _Air_Loop_Name_1 {
                get {
                    try {
                        return ((string)(this[this.tableZoneExProps._Air_Loop_Name_1Column]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'Air Loop Name-1\' in table \'ZoneExProps\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tableZoneExProps._Air_Loop_Name_1Column] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public string _Air_Loop_Template_1 {
                get {
                    try {
                        return ((string)(this[this.tableZoneExProps._Air_Loop_Template_1Column]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'Air Loop Template-1\' in table \'ZoneExProps\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tableZoneExProps._Air_Loop_Template_1Column] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public string _Water_Loop_Name_1 {
                get {
                    try {
                        return ((string)(this[this.tableZoneExProps._Water_Loop_Name_1Column]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'Water Loop Name-1\' in table \'ZoneExProps\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tableZoneExProps._Water_Loop_Name_1Column] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public bool IsSpacesNull() {
                return this.IsNull(this.tableZoneExProps.SpacesColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public void SetSpacesNull() {
                this[this.tableZoneExProps.SpacesColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public bool IsContained_building_storiesNull() {
                return this.IsNull(this.tableZoneExProps.Contained_building_storiesColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public void SetContained_building_storiesNull() {
                this[this.tableZoneExProps.Contained_building_storiesColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public bool IsAreaNull() {
                return this.IsNull(this.tableZoneExProps.AreaColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public void SetAreaNull() {
                this[this.tableZoneExProps.AreaColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public bool IsVolumeNull() {
                return this.IsNull(this.tableZoneExProps.VolumeColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public void SetVolumeNull() {
                this[this.tableZoneExProps.VolumeColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public bool IsOccupancy_TemplateNull() {
                return this.IsNull(this.tableZoneExProps.Occupancy_TemplateColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public void SetOccupancy_TemplateNull() {
                this[this.tableZoneExProps.Occupancy_TemplateColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public bool IsZone_Daylighting_GroupNull() {
                return this.IsNull(this.tableZoneExProps.Zone_Daylighting_GroupColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public void SetZone_Daylighting_GroupNull() {
                this[this.tableZoneExProps.Zone_Daylighting_GroupColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public bool IsZone_Natural_Ventilation_GroupNull() {
                return this.IsNull(this.tableZoneExProps.Zone_Natural_Ventilation_GroupColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public void SetZone_Natural_Ventilation_GroupNull() {
                this[this.tableZoneExProps.Zone_Natural_Ventilation_GroupColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public bool IsZone_SHW_GroupNull() {
                return this.IsNull(this.tableZoneExProps.Zone_SHW_GroupColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public void SetZone_SHW_GroupNull() {
                this[this.tableZoneExProps.Zone_SHW_GroupColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public bool IsZone_RFG_GroupNull() {
                return this.IsNull(this.tableZoneExProps.Zone_RFG_GroupColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public void SetZone_RFG_GroupNull() {
                this[this.tableZoneExProps.Zone_RFG_GroupColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public bool IsZone_HVAC_Group_NameNull() {
                return this.IsNull(this.tableZoneExProps.Zone_HVAC_Group_NameColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public void SetZone_HVAC_Group_NameNull() {
                this[this.tableZoneExProps.Zone_HVAC_Group_NameColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public bool Is_Zone_HVAC_Group_Name_1Null() {
                return this.IsNull(this.tableZoneExProps._Zone_HVAC_Group_Name_1Column);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public void Set_Zone_HVAC_Group_Name_1Null() {
                this[this.tableZoneExProps._Zone_HVAC_Group_Name_1Column] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public bool IsZone_HVAC_Group_TemplateNull() {
                return this.IsNull(this.tableZoneExProps.Zone_HVAC_Group_TemplateColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public void SetZone_HVAC_Group_TemplateNull() {
                this[this.tableZoneExProps.Zone_HVAC_Group_TemplateColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public bool IsAir_Loop_NameNull() {
                return this.IsNull(this.tableZoneExProps.Air_Loop_NameColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public void SetAir_Loop_NameNull() {
                this[this.tableZoneExProps.Air_Loop_NameColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public bool IsAir_Loop_TemplateNull() {
                return this.IsNull(this.tableZoneExProps.Air_Loop_TemplateColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public void SetAir_Loop_TemplateNull() {
                this[this.tableZoneExProps.Air_Loop_TemplateColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public bool IsWater_Loop_NameNull() {
                return this.IsNull(this.tableZoneExProps.Water_Loop_NameColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public void SetWater_Loop_NameNull() {
                this[this.tableZoneExProps.Water_Loop_NameColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public bool IsLibraryNameNull() {
                return this.IsNull(this.tableZoneExProps.LibraryNameColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public void SetLibraryNameNull() {
                this[this.tableZoneExProps.LibraryNameColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public bool Is_Spaces_1Null() {
                return this.IsNull(this.tableZoneExProps._Spaces_1Column);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public void Set_Spaces_1Null() {
                this[this.tableZoneExProps._Spaces_1Column] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public bool Is_Contained_building_stories_1Null() {
                return this.IsNull(this.tableZoneExProps._Contained_building_stories_1Column);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public void Set_Contained_building_stories_1Null() {
                this[this.tableZoneExProps._Contained_building_stories_1Column] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public bool Is_Occupancy_Template_1Null() {
                return this.IsNull(this.tableZoneExProps._Occupancy_Template_1Column);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public void Set_Occupancy_Template_1Null() {
                this[this.tableZoneExProps._Occupancy_Template_1Column] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public bool Is_Zone_Natural_Ventilation_Group_1Null() {
                return this.IsNull(this.tableZoneExProps._Zone_Natural_Ventilation_Group_1Column);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public void Set_Zone_Natural_Ventilation_Group_1Null() {
                this[this.tableZoneExProps._Zone_Natural_Ventilation_Group_1Column] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public bool Is_Zone_SHW_Group_1Null() {
                return this.IsNull(this.tableZoneExProps._Zone_SHW_Group_1Column);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public void Set_Zone_SHW_Group_1Null() {
                this[this.tableZoneExProps._Zone_SHW_Group_1Column] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public bool Is_Zone_RFG_Group_1Null() {
                return this.IsNull(this.tableZoneExProps._Zone_RFG_Group_1Column);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public void Set_Zone_RFG_Group_1Null() {
                this[this.tableZoneExProps._Zone_RFG_Group_1Column] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public bool Is_Zone_HVAC_Group_Template_1Null() {
                return this.IsNull(this.tableZoneExProps._Zone_HVAC_Group_Template_1Column);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public void Set_Zone_HVAC_Group_Template_1Null() {
                this[this.tableZoneExProps._Zone_HVAC_Group_Template_1Column] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public bool Is_Air_Loop_Name_1Null() {
                return this.IsNull(this.tableZoneExProps._Air_Loop_Name_1Column);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public void Set_Air_Loop_Name_1Null() {
                this[this.tableZoneExProps._Air_Loop_Name_1Column] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public bool Is_Air_Loop_Template_1Null() {
                return this.IsNull(this.tableZoneExProps._Air_Loop_Template_1Column);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public void Set_Air_Loop_Template_1Null() {
                this[this.tableZoneExProps._Air_Loop_Template_1Column] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public bool Is_Water_Loop_Name_1Null() {
                return this.IsNull(this.tableZoneExProps._Water_Loop_Name_1Column);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public void Set_Water_Loop_Name_1Null() {
                this[this.tableZoneExProps._Water_Loop_Name_1Column] = global::System.Convert.DBNull;
            }
        }
        
        /// <summary>
        ///Row event argument class
        ///</summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
        public class ZoneExPropsRowChangeEvent : global::System.EventArgs {
            
            private ZoneExPropsRow eventRow;
            
            private global::System.Data.DataRowAction eventAction;
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public ZoneExPropsRowChangeEvent(ZoneExPropsRow row, global::System.Data.DataRowAction action) {
                this.eventRow = row;
                this.eventAction = action;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public ZoneExPropsRow Row {
                get {
                    return this.eventRow;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public global::System.Data.DataRowAction Action {
                get {
                    return this.eventAction;
                }
            }
        }
    }
}

#pragma warning restore 1591