//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

// 
// This source code was auto-generated by xsd, Version=4.6.1055.0.
// 


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
[System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
public partial class arguments {
    
    private argumentsArgument[] argumentField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("argument")]
    public argumentsArgument[] argument {
        get {
            return this.argumentField;
        }
        set {
            this.argumentField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class argumentsArgument {
    
    private string nameField;
    
    private string display_nameField;
    
    private object short_nameField;
    
    private string descriptionField;
    
    private argumentsArgumentType typeField;
    
    private string unitsField;
    
    private bool requiredField;
    
    private bool model_dependentField;
    
    private string default_valueField;
    
    private argumentsArgumentChoice[] choicesField;
    
    private string min_valueField;
    
    private string max_valueField;
    
    public argumentsArgument() {
        this.model_dependentField = false;
    }
    
    /// <remarks/>
    public string name {
        get {
            return this.nameField;
        }
        set {
            this.nameField = value;
        }
    }
    
    /// <remarks/>
    public string display_name {
        get {
            return this.display_nameField;
        }
        set {
            this.display_nameField = value;
        }
    }
    
    /// <remarks/>
    public object short_name {
        get {
            return this.short_nameField;
        }
        set {
            this.short_nameField = value;
        }
    }
    
    /// <remarks/>
    public string description {
        get {
            return this.descriptionField;
        }
        set {
            this.descriptionField = value;
        }
    }
    
    /// <remarks/>
    public argumentsArgumentType type {
        get {
            return this.typeField;
        }
        set {
            this.typeField = value;
        }
    }
    
    /// <remarks/>
    public string units {
        get {
            return this.unitsField;
        }
        set {
            this.unitsField = value;
        }
    }
    
    /// <remarks/>
    public bool required {
        get {
            return this.requiredField;
        }
        set {
            this.requiredField = value;
        }
    }
    
    /// <remarks/>
    public bool model_dependent {
        get {
            return this.model_dependentField;
        }
        set {
            this.model_dependentField = value;
        }
    }
    
    /// <remarks/>
    public string default_value {
        get {
            return this.default_valueField;
        }
        set {
            this.default_valueField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayItemAttribute("choice", IsNullable=false)]
    public argumentsArgumentChoice[] choices {
        get {
            return this.choicesField;
        }
        set {
            this.choicesField = value;
        }
    }
    
    /// <remarks/>
    public string min_value {
        get {
            return this.min_valueField;
        }
        set {
            this.min_valueField = value;
        }
    }
    
    /// <remarks/>
    public string max_value {
        get {
            return this.max_valueField;
        }
        set {
            this.max_valueField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public enum argumentsArgumentType {
    
    /// <remarks/>
    Boolean,
    
    /// <remarks/>
    Double,
    
    /// <remarks/>
    Integer,
    
    /// <remarks/>
    String,
    
    /// <remarks/>
    Choice,
    
    /// <remarks/>
    Path,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class argumentsArgumentChoice {
    
    private string valueField;
    
    private string display_nameField;
    
    /// <remarks/>
    public string value {
        get {
            return this.valueField;
        }
        set {
            this.valueField = value;
        }
    }
    
    /// <remarks/>
    public string display_name {
        get {
            return this.display_nameField;
        }
        set {
            this.display_nameField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
[System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
public partial class outputs {
    
    private outputsOutput[] outputField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("output")]
    public outputsOutput[] output {
        get {
            return this.outputField;
        }
        set {
            this.outputField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class outputsOutput {
    
    private string nameField;
    
    private string display_nameField;
    
    private object short_nameField;
    
    private string descriptionField;
    
    private outputsOutputType typeField;
    
    private string unitsField;
    
    private bool model_dependentField;
    
    public outputsOutput() {
        this.model_dependentField = false;
    }
    
    /// <remarks/>
    public string name {
        get {
            return this.nameField;
        }
        set {
            this.nameField = value;
        }
    }
    
    /// <remarks/>
    public string display_name {
        get {
            return this.display_nameField;
        }
        set {
            this.display_nameField = value;
        }
    }
    
    /// <remarks/>
    public object short_name {
        get {
            return this.short_nameField;
        }
        set {
            this.short_nameField = value;
        }
    }
    
    /// <remarks/>
    public string description {
        get {
            return this.descriptionField;
        }
        set {
            this.descriptionField = value;
        }
    }
    
    /// <remarks/>
    public outputsOutputType type {
        get {
            return this.typeField;
        }
        set {
            this.typeField = value;
        }
    }
    
    /// <remarks/>
    public string units {
        get {
            return this.unitsField;
        }
        set {
            this.unitsField = value;
        }
    }
    
    /// <remarks/>
    public bool model_dependent {
        get {
            return this.model_dependentField;
        }
        set {
            this.model_dependentField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public enum outputsOutputType {
    
    /// <remarks/>
    Boolean,
    
    /// <remarks/>
    Double,
    
    /// <remarks/>
    Integer,
    
    /// <remarks/>
    String,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
[System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
public partial class masterguide_csi_values {
    
    private object[] masterguide_csi_valueField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("masterguide_csi_value")]
    public object[] masterguide_csi_value {
        get {
            return this.masterguide_csi_valueField;
        }
        set {
            this.masterguide_csi_valueField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
[System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
public partial class source {
    
    private string manufacturerField;
    
    private object modelField;
    
    private object serial_noField;
    
    private object yearField;
    
    private object urlField;
    
    /// <remarks/>
    public string manufacturer {
        get {
            return this.manufacturerField;
        }
        set {
            this.manufacturerField = value;
        }
    }
    
    /// <remarks/>
    public object model {
        get {
            return this.modelField;
        }
        set {
            this.modelField = value;
        }
    }
    
    /// <remarks/>
    public object serial_no {
        get {
            return this.serial_noField;
        }
        set {
            this.serial_noField = value;
        }
    }
    
    /// <remarks/>
    public object year {
        get {
            return this.yearField;
        }
        set {
            this.yearField = value;
        }
    }
    
    /// <remarks/>
    public object url {
        get {
            return this.urlField;
        }
        set {
            this.urlField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
[System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
public partial class provenances {
    
    private provenancesProvenance[] provenanceField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("provenance")]
    public provenancesProvenance[] provenance {
        get {
            return this.provenanceField;
        }
        set {
            this.provenanceField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class provenancesProvenance {
    
    private string authorField;
    
    private System.DateTime datetimeField;
    
    private string commentField;
    
    /// <remarks/>
    public string author {
        get {
            return this.authorField;
        }
        set {
            this.authorField = value;
        }
    }
    
    /// <remarks/>
    public System.DateTime datetime {
        get {
            return this.datetimeField;
        }
        set {
            this.datetimeField = value;
        }
    }
    
    /// <remarks/>
    public string comment {
        get {
            return this.commentField;
        }
        set {
            this.commentField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
[System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
public partial class tags {
    
    private string[] tagField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("tag")]
    public string[] tag {
        get {
            return this.tagField;
        }
        set {
            this.tagField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
[System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
public partial class attributes {
    
    private attributesAttribute[] attributeField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("attribute")]
    public attributesAttribute[] attribute {
        get {
            return this.attributeField;
        }
        set {
            this.attributeField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class attributesAttribute {
    
    private string nameField;
    
    private string valueField;
    
    private attributesAttributeDatatype datatypeField;
    
    private string unitsField;
    
    /// <remarks/>
    public string name {
        get {
            return this.nameField;
        }
        set {
            this.nameField = value;
        }
    }
    
    /// <remarks/>
    public string value {
        get {
            return this.valueField;
        }
        set {
            this.valueField = value;
        }
    }
    
    /// <remarks/>
    public attributesAttributeDatatype datatype {
        get {
            return this.datatypeField;
        }
        set {
            this.datatypeField = value;
        }
    }
    
    /// <remarks/>
    public string units {
        get {
            return this.unitsField;
        }
        set {
            this.unitsField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public enum attributesAttributeDatatype {
    
    /// <remarks/>
    @float,
    
    /// <remarks/>
    integer,
    
    /// <remarks/>
    @string,
    
    /// <remarks/>
    boolean,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
[System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
public partial class files {
    
    private filesFile[] fileField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("file")]
    public filesFile[] file {
        get {
            return this.fileField;
        }
        set {
            this.fileField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class filesFile {
    
    private filesFileVersion versionField;
    
    private string filenameField;
    
    private string filetypeField;
    
    private filesFileUsage_type usage_typeField;
    
    private string checksumField;
    
    /// <remarks/>
    public filesFileVersion version {
        get {
            return this.versionField;
        }
        set {
            this.versionField = value;
        }
    }
    
    /// <remarks/>
    public string filename {
        get {
            return this.filenameField;
        }
        set {
            this.filenameField = value;
        }
    }
    
    /// <remarks/>
    public string filetype {
        get {
            return this.filetypeField;
        }
        set {
            this.filetypeField = value;
        }
    }
    
    /// <remarks/>
    public filesFileUsage_type usage_type {
        get {
            return this.usage_typeField;
        }
        set {
            this.usage_typeField = value;
        }
    }
    
    /// <remarks/>
    public string checksum {
        get {
            return this.checksumField;
        }
        set {
            this.checksumField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class filesFileVersion {
    
    private string software_programField;
    
    private string identifierField;
    
    private object min_compatibleField;
    
    private object max_compatibleField;
    
    /// <remarks/>
    public string software_program {
        get {
            return this.software_programField;
        }
        set {
            this.software_programField = value;
        }
    }
    
    /// <remarks/>
    public string identifier {
        get {
            return this.identifierField;
        }
        set {
            this.identifierField = value;
        }
    }
    
    /// <remarks/>
    public object min_compatible {
        get {
            return this.min_compatibleField;
        }
        set {
            this.min_compatibleField = value;
        }
    }
    
    /// <remarks/>
    public object max_compatible {
        get {
            return this.max_compatibleField;
        }
        set {
            this.max_compatibleField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public enum filesFileUsage_type {
    
    /// <remarks/>
    script,
    
    /// <remarks/>
    test,
    
    /// <remarks/>
    resource,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
[System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
public partial class costs {
    
    private costsCost[] costField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("cost")]
    public costsCost[] cost {
        get {
            return this.costField;
        }
        set {
            this.costField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class costsCost {
    
    private string instance_nameField;
    
    private costsCostCost_type cost_typeField;
    
    private object categoryField;
    
    private float valueField;
    
    private object unitsField;
    
    private object intervalField;
    
    private costsCostInterval_units interval_unitsField;
    
    private bool interval_unitsFieldSpecified;
    
    private int yearField;
    
    private bool yearFieldSpecified;
    
    private object start_yearField;
    
    private object end_yearField;
    
    private object locationField;
    
    private object currencyField;
    
    private string sourceField;
    
    private object reference_component_nameField;
    
    private object reference_component_idField;
    
    /// <remarks/>
    public string instance_name {
        get {
            return this.instance_nameField;
        }
        set {
            this.instance_nameField = value;
        }
    }
    
    /// <remarks/>
    public costsCostCost_type cost_type {
        get {
            return this.cost_typeField;
        }
        set {
            this.cost_typeField = value;
        }
    }
    
    /// <remarks/>
    public object category {
        get {
            return this.categoryField;
        }
        set {
            this.categoryField = value;
        }
    }
    
    /// <remarks/>
    public float value {
        get {
            return this.valueField;
        }
        set {
            this.valueField = value;
        }
    }
    
    /// <remarks/>
    public object units {
        get {
            return this.unitsField;
        }
        set {
            this.unitsField = value;
        }
    }
    
    /// <remarks/>
    public object interval {
        get {
            return this.intervalField;
        }
        set {
            this.intervalField = value;
        }
    }
    
    /// <remarks/>
    public costsCostInterval_units interval_units {
        get {
            return this.interval_unitsField;
        }
        set {
            this.interval_unitsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool interval_unitsSpecified {
        get {
            return this.interval_unitsFieldSpecified;
        }
        set {
            this.interval_unitsFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    public int year {
        get {
            return this.yearField;
        }
        set {
            this.yearField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool yearSpecified {
        get {
            return this.yearFieldSpecified;
        }
        set {
            this.yearFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    public object start_year {
        get {
            return this.start_yearField;
        }
        set {
            this.start_yearField = value;
        }
    }
    
    /// <remarks/>
    public object end_year {
        get {
            return this.end_yearField;
        }
        set {
            this.end_yearField = value;
        }
    }
    
    /// <remarks/>
    public object location {
        get {
            return this.locationField;
        }
        set {
            this.locationField = value;
        }
    }
    
    /// <remarks/>
    public object currency {
        get {
            return this.currencyField;
        }
        set {
            this.currencyField = value;
        }
    }
    
    /// <remarks/>
    public string source {
        get {
            return this.sourceField;
        }
        set {
            this.sourceField = value;
        }
    }
    
    /// <remarks/>
    public object reference_component_name {
        get {
            return this.reference_component_nameField;
        }
        set {
            this.reference_component_nameField = value;
        }
    }
    
    /// <remarks/>
    public object reference_component_id {
        get {
            return this.reference_component_idField;
        }
        set {
            this.reference_component_idField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public enum costsCostCost_type {
    
    /// <remarks/>
    low,
    
    /// <remarks/>
    high,
    
    /// <remarks/>
    average,
    
    /// <remarks/>
    estimate,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public enum costsCostInterval_units {
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("year(s)")]
    years,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("month(s)")]
    months,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("day(s)")]
    days,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
[System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
public partial class measure {
    
    private string schema_versionField;
    
    private object errorField;
    
    private string nameField;
    
    private string uidField;
    
    private string version_idField;
    
    private System.DateTime version_modifiedField;
    
    private bool version_modifiedFieldSpecified;
    
    private string xml_checksumField;
    
    private string class_nameField;
    
    private string display_nameField;
    
    private object short_nameField;
    
    private string descriptionField;
    
    private string modeler_descriptionField;
    
    private argumentsArgument[] argumentsField;
    
    private outputsOutput[] outputsField;
    
    private provenancesProvenance[] provenancesField;
    
    private string[] tagsField;
    
    private attributesAttribute[] attributesField;
    
    private filesFile[] filesField;
    
    public measure() {
        this.schema_versionField = "3.0";
    }
    
    /// <remarks/>
    public string schema_version {
        get {
            return this.schema_versionField;
        }
        set {
            this.schema_versionField = value;
        }
    }
    
    /// <remarks/>
    public object error {
        get {
            return this.errorField;
        }
        set {
            this.errorField = value;
        }
    }
    
    /// <remarks/>
    public string name {
        get {
            return this.nameField;
        }
        set {
            this.nameField = value;
        }
    }
    
    /// <remarks/>
    public string uid {
        get {
            return this.uidField;
        }
        set {
            this.uidField = value;
        }
    }
    
    /// <remarks/>
    public string version_id {
        get {
            return this.version_idField;
        }
        set {
            this.version_idField = value;
        }
    }
    
    /// <remarks/>
    public System.DateTime version_modified {
        get {
            return this.version_modifiedField;
        }
        set {
            this.version_modifiedField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool version_modifiedSpecified {
        get {
            return this.version_modifiedFieldSpecified;
        }
        set {
            this.version_modifiedFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    public string xml_checksum {
        get {
            return this.xml_checksumField;
        }
        set {
            this.xml_checksumField = value;
        }
    }
    
    /// <remarks/>
    public string class_name {
        get {
            return this.class_nameField;
        }
        set {
            this.class_nameField = value;
        }
    }
    
    /// <remarks/>
    public string display_name {
        get {
            return this.display_nameField;
        }
        set {
            this.display_nameField = value;
        }
    }
    
    /// <remarks/>
    public object short_name {
        get {
            return this.short_nameField;
        }
        set {
            this.short_nameField = value;
        }
    }
    
    /// <remarks/>
    public string description {
        get {
            return this.descriptionField;
        }
        set {
            this.descriptionField = value;
        }
    }
    
    /// <remarks/>
    public string modeler_description {
        get {
            return this.modeler_descriptionField;
        }
        set {
            this.modeler_descriptionField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayItemAttribute("argument", IsNullable=false)]
    public argumentsArgument[] arguments {
        get {
            return this.argumentsField;
        }
        set {
            this.argumentsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayItemAttribute("output", IsNullable=false)]
    public outputsOutput[] outputs {
        get {
            return this.outputsField;
        }
        set {
            this.outputsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayItemAttribute("provenance", IsNullable=false)]
    public provenancesProvenance[] provenances {
        get {
            return this.provenancesField;
        }
        set {
            this.provenancesField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayItemAttribute("tag", IsNullable=false)]
    public string[] tags {
        get {
            return this.tagsField;
        }
        set {
            this.tagsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayItemAttribute("attribute", IsNullable=false)]
    public attributesAttribute[] attributes {
        get {
            return this.attributesField;
        }
        set {
            this.attributesField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayItemAttribute("file", IsNullable=false)]
    public filesFile[] files {
        get {
            return this.filesField;
        }
        set {
            this.filesField = value;
        }
    }
}
